[package]
name = "launch"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { path = "../model/" }
parse = { path = "../parse/" }
download = { path = "../download/" }
clap = { version = "4.5" }
zip = { version = "2.1" }
